language: python
python:
- 3.4
- 3.5
- 3.6
env:
- DJANGO=2.0
install:
- pip install -q Django~=$DJANGO.0
script:
- python runtests.py
deploy:
  provider: pypi
  user: bradleyg
  on:
    tags: true
  password:
    secure: a+Xq1e2yuTNtjcJ5wJ5oQxsfx/lqwYD7dbFEqdoazpkflZ8UA9AErgL2quAbo0RIRKFDBXwRNUspRtQdQ6TClKxgzsaa4AQEPWxYxx353kYMdhPjXe0/ib1rWJ0eefs/RDu0mndpQu/slNjxzV351QXPoPKo9tHgnLHWoNzYAzs=
